language: ruby
cache: bundler
rvm:
    - 2.4
sudo: false
env:
    global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
install: gem install html-proofer
script: htmlproofer --http-status-ignore 999 index.html
